name: Upload

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      id: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV

    - name: add cr
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        wget -O $GITHUB_WORKSPACE/bin/cr https://github.com/calcit-lang/calcit/releases/download/0.6.18/cr
        chmod +x $GITHUB_WORKSPACE/bin/cr
        echo "::add-path::$GITHUB_WORKSPACE/bin"

    - name: "prepare modules"
      run: >
        mkdir -p ~/.config/calcit/modules/ && cd ~/.config/calcit/modules/
        && git clone https://github.com/calcit-lang/lilac.git
        && git clone https://github.com/Respo/respo-router.calcit.git

    - name: "compiles to js"
      run: >
        cr --emit-js --once
        && yarn && yarn bundle-main
