name: Upload

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare yarn@4.12.0 --activate
        yarn --version

    - uses: calcit-lang/setup-cr@0.0.9

    - name: Install deps
      run: caps --ci && yarn install --immutable

    - name: Compile to JavaScript
      run: cr js
